### ISSUE TITLE
Add user permissions to commit

### ISSUE THREAD

**Issue by kyle-winters** [CiscoSE/MaxmindAsnImporter#2]
Hey @TheAlanNix hope you are well. @RichWellum needs permissions to commit to this repo. Are you able to provide?

**Comment by TheAlanNix** [comment]
Unfortunately I no longer have access, one of the admins of CiscoSE will need to add him.

**Comment by kyle-winters** [comment]
No worries Alan. 

Hey @cmlccie do you think you could help Rich out here?
